### ISSUE TITLE
Stuck in capslock

### ISSUE THREAD

**Issue by 0xR** [susam/uncap#12]
Capslock was on when I ran uncap.exe.

NOW I'M STUCK WITH CAPSLOCK

**Comment by extremepayne** [comment]
Try rebooting your computer. This might help. If not (and you're on windows), you can try [this](https://www.groovypost.com/howto/shift-key-disable-capslock/). If you're on some other kind of system, you can use uncap's more advanced functionality to temporarily remap another key to caps lock in order to turn it off.

As far as permanent fixes go, I don't think it's an issue with uncap. Just turn off caps lock before you run it. It's such an edge case that I don't think it's necessary for uncap to turn off caps lock before performing the remap. If that's what you think the behavior should be, you could try fixing it yourself and opening a PR.

**Comment by susam** [comment]
Enter this command to kill Caps Lock:

```cmd
uncap -k
```

After that you can toggle Caps Lock off and start Uncap again.
