### ISSUE TITLE
Combo?

### ISSUE THREAD

**Issue by gerroon** [susam/uncap#2]
Hi

Can you please tell me how i can do combo assignment? For instance, Capslock to Win+F11 or so.

thanks

**Comment by susam** [comment]
Hi @gerroon,

Uncap has not been designed to map a key to a combination of keys.

Regards,
Susam

**Comment by sisrfeng** [comment]
This may be a similar problem:  
With powertoy, I map `Capslock` to `VK136` (decimal, should be vk88 in autohotkey' s script), and in my_key.ahk, I have `VK88 & a::send XXX` and `VK88 & z::send XXXX`... Then I have a least 26 more shortcuts available!!

But with `uncap 0x14:0x88` instead of powertoy(I can't use it on the old win10 on my office PC), `VK88 & a` does not work, though autohotkey can detect vk88 when I press `CapsLock`
Could you please give me some advice on that?
